-- Lisää INSERT INTO lauseet tähän tiedostoon
INSERT INTO Ryhma (id, nimi, kuvaus) VALUES ('1', 'Admin', 'Ylläpitäjät, rajaton valta.');
INSERT INTO Ryhma (id, nimi, kuvaus) VALUES ('2', 'Käyttäjä', 'Foorumin keskustelijat, voivat tehdä asioita');
INSERT INTO Ryhma (id, nimi, kuvaus) VALUES ('3', 'Aresti', 'Foorumin keskustelijat, jotka ovat tehneet vääriä asioita');
INSERT INTO Kayttaja (id, nimi, salasana, ryhma_id) VALUES ('1', 'Make-Viljami', 'lol', '1');
INSERT INTO Aihe (id, nimi, kuvaus) VALUES ('0', 'Kebab', 'Eilen oli tanaan ei');
INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('0', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('1', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('2', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('3', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('4', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('5', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('6', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('7', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('8', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('9', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('10', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('11', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('12', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('13', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('14', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('15', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('16', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('17', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('18', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('19', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
-- INSERT INTO Kirjoitus (id, aihe_id, nimi, sisalto, julkaistu, julkaisija) VALUES ('20', '0', 'Trolling is a art', 'Trolo', NOW(), '1');
INSERT INTO Kommentti (id, kirjoitus_id, sisalto, julkaistu, julkaisija) VALUES ('0', '0', 'lol', NOW(), '1');