-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Aihe CASCADE;
DROP TABLE IF EXISTS Ryhma CASCADE;
DROP TABLE IF EXISTS Kirjoitus CASCADE;
DROP TABLE IF EXISTS Kayttajaryhma CASCADE;
DROP TABLE IF EXISTS Kommentti CASCADE;